# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

 plugins: jekyll-admin]
 # This will require each of these plugins automatically.
 
# Site settings
title: Ansel Lim
email: ansellim@icloud.com
description: > # this means to ignore newlines until "baseurl:"
  Ansel Lim, fourth-year medical student of clinical medicine, part-time trainee in anatomical pathology, and researcher in quantitative pathology
baseurl: "" # the subpath of your site, e.g. /blog
url: "trisectedangle.github.io" # the base hostname & protocol for your site
twitter_username: trisectedangle
github_username:  trisectedangle

# Build settings
markdown: kramdown
